environment:
  nodejs_version: "14.17.6"

image:
  - Ubuntu
  - Visual Studio 2019

branches:
  only:
    - main

install:
  - sh: nvm install --lts
  - sh: PACK_VER=$(python3 -c "import json; x=open(\"package.json\",\"r\").read(); print(json.loads(x)[\"version\"]);")
  - ps: if ($isWindows) { Update-NodeJsInstallation $env:nodejs_version }
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - yarn

test_script:
  - node --version
  - yarn run test
  - sh: echo $PACK_VER
  - ps: if ($isWindows) { echo $env:package_version }

before_build:
  - cmd: yarn run package-win
  - sh: yarn run package-linux

build_script:
  # Creates Tar Package For Linux.
  - sh: mv release-builds/desmos* release-builds/desmos-offline-mode
  - sh: cp resources/icon.png resources/desmos-app.desktop release-builds/desmos-offline-mode
  - sh: cd release-builds && tar czf ./desmos-app-linux.tar.gz desmos-offline-mode
  - sh: cd .. && ls release-builds/

  # Creates Exe Setup with Inno Setup for Windows.
  - ps: if($isWindows) { copy .\resources\desmos_file.ico .\release-builds\desmos-offline-mode-win32-ia32\ }
  - ps: if ($isWindows) { (Get-Content -Raw -Path desmos-setup.iss) -replace "APP_VER",('"'+$env:package_version+'"') | Set-Content -Path desmos-setup.iss }
  - cmd: C:\"Program Files (x86)"\"Inno Setup 6"\ISCC.exe .\desmos-setup.iss
  - ps: if ($isWindows) { move Output\desmos-setup.exe release-builds\desmos-setup.exe }
  - cmd: rmdir Output
  - ps: if ($isWindows) { Compress-Archive release-builds\desmos-setup.exe release-builds\desmos-app-win32.zip }
  - cmd: dir release-builds

artifacts:
  - path: release-builds\*.zip
    name: desmos-app-win32

  - path: release-builds\*.tar.gz
    name: desmos-app-linux

deploy:
  tag: v$(package_version)
  release: Desmos-Offline-Mode-v$(package_version)
  description: "Update $(package_version)"
  provider: GitHub
  auth_token:
    secure: a89z3Lqf4pRPewcATJLFtVsgEfnUxKPi7/B9+NLIKqIKGMNMm60tTQIkETUPRNis
  artifact: desmos-app-win32, desmos-app-linux
  draft: false
  prerelease: false
  on:
    branch: main
    APPVEYOR_REPO_TAG: true